[build]
  command = "yarn install --frozen-lockfile && yarn add @types/d3 @types/node @tanstack/react-table @tanstack/react-virtual react-grid-layout react-resizable --dev && yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.19"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false 